export const GET_ARTICLES_START = 'GET_ARTICLES_START';
export const GET_ARTICLES_SUCCEED = 'GET_ARTICLES_SUCCEED';
export const GET_ARTICLES_FAIL = 'GET_ARTICLES_FAIL';

export const GET_ARTICLE_BY_ID_START = 'GET_ARTICLE_BY_ID_START';
export const GET_ARTICLE_BY_ID_SUCCEED = 'GET_ARTICLE_BY_ID_SUCCEED';
export const GET_ARTICLE_BY_ID_FAIL = 'GET_ARTICLE_BY_ID_FAIL';
